### ISSUE TITLE
Add example how to add a checklist in README

### ISSUE THREAD

**Issue by toabctl** [kewisch/jirablueprint#2]
Is it possible to add checklists with a template? If so, would be good to have that as an example.

**Comment by kewisch** [comment]
I don't think I have checklists enabled on my project to find out, what is your project key?

**Comment by kewisch** [comment]
Ah I was just on the wrong instance. Here you go:

```yaml
test:
  issues:
    - fields:
        issuetype: Task
        summary: Test
        customfield_10039: "#Default checklist\n* [open] Test1\n* [open] Test 2"
```

Unfortunately you can't just use "Checklist" instead of customfield_10039, because there are multiple fields called Checklist. Also unfortunately the checklist format is somewhat custom, so you can't just use an array.  Potentially we could add some sugar for textarea fields called "Checklist Text", but at least you have a way to do this for now :)


Best way to find out:
* Create an issue that has what you need
* `jirabp issue ISSUEKEY-123` 
* Find the key that holds what you want
* Use the pretty name for the field and see if you can set it. Use the customfield name if necessary.
